"""
Generated by: budget_crawler/dfg_projection_extractor.py
DO NOT HAND-EDIT — rerun the script to regenerate output CSV.

Extracts MWCD ministry projection vs Finance Ministry actual allocation
from DFG committee report PDFs across multiple years.
"""

import argparse
import csv
import json
import re
from pathlib import Path

import pdfplumber


# Scheme name patterns
_ANGANWADI_RE = re.compile(
    r"(saksham\s+)?anganwadi\s*(services?|cum|and|&|\+|poshan)?",
    re.IGNORECASE,
)
_ICDS_RE = re.compile(r"\bicds\b|\bumbrella\s+icds\b", re.IGNORECASE)

# A rupee figure: digits with exactly 2 decimal places
_AMOUNT_RE = re.compile(r"[\d,]+\.\d{2}")


def _parse_float(s):
    if s is None:
        return None
    cleaned = re.sub(r"[^\d.]", "", s)
    try:
        return round(float(cleaned), 2)
    except ValueError:
        return None


def _extract_amounts_from_line(line, min_val=None):
    # Strip percentage markers before extracting, to avoid matching e.g. "45.63%"
    clean = re.sub(r"[\d,]+\.?\d*\s*%", "", line)
    amounts = [_parse_float(m) for m in _AMOUNT_RE.findall(clean)]
    if min_val is not None:
        amounts = [a for a in amounts if a and a >= min_val]
    return amounts


def _year_from_title(title):
    m = re.search(r"(\d{4}[-–]\d{2,4})", title)
    if m:
        raw = m.group(1)
        parts = re.split(r"[-–]", raw)
        if len(parts) == 2:
            start = parts[0]
            end = parts[1]
            if len(end) == 2:
                end = start[:2] + end
            return f"{start}-{end[-2:]}"
    return None


def extract_from_pdf(pdf_path):
    """
    Returns (mwcd_projected_cr, finance_allocated_cr, confidence) or (None, None, 'none').

    Strategy 1 (high): table with 'Projections to MoF' column — Report 365/377 style.
    Strategy 2 (medium): two-column 'Projected Demand | Actual Allocation' table — Report 338 style.
    Strategy 3 (low): find anganwadi-adjacent lines with two large amounts.
    """
    try:
        with pdfplumber.open(str(pdf_path)) as pdf:
            pages_text = []
            for page in pdf.pages:
                t = page.extract_text()
                pages_text.append(t or "")
    except Exception as e:
        return None, None, "none", f"pdfplumber error: {e}"

    full_text = "\n".join(pages_text)
    if not full_text.strip():
        return None, None, "none", "no text extracted (possibly scanned)"

    # ---- Strategy 1: TABLE-3 / Projections to MoF style ----
    # Look for pages that mention "Projections to MoF" or "Projections to Ministry of Finance"
    mof_proj_re = re.compile(r"projections?\s+to\s+(mof|ministry\s+of\s+finance)", re.IGNORECASE)
    for page_text in pages_text:
        if not mof_proj_re.search(page_text):
            continue
        lines = page_text.splitlines()
        for i, line in enumerate(lines):
            if not (_ANGANWADI_RE.search(line) or _ICDS_RE.search(line)):
                continue
            # Gather amounts from this line and next 1 line only (table may wrap mid-word)
            combined = " ".join(lines[i : i + 2])
            # Only crore-scale figures (>= 100); strip percentages first
            amounts = _extract_amounts_from_line(combined, min_val=100)
            # Table columns: actual, BE, RE, projection_to_MoF, BE_allocated
            # Need at least 4 amounts; projection is 2nd-to-last, allocated is last
            if len(amounts) >= 4:
                projected = amounts[-2]
                allocated = amounts[-1]
                if projected and allocated and projected > allocated:
                    return projected, allocated, "high", None
            # Fallback: if only 2 large amounts found
            if len(amounts) == 2 and amounts[0] > amounts[1]:
                return amounts[0], amounts[1], "high", None

    # ---- Strategy 2: Projected Demand | Actual Allocation table ----
    proj_alloc_re = re.compile(r"projected\s+(demand|be\b)", re.IGNORECASE)
    actual_alloc_re = re.compile(r"actual\s+allocation|allocated\s+be\b", re.IGNORECASE)
    # Also match integers (column-misaligned PDFs omit decimal for split tokens)
    _INT_OR_FLOAT_RE = re.compile(r"\b\d{3,}(?:\.\d{1,2})?\b")
    for page_text in pages_text:
        if not (proj_alloc_re.search(page_text) and actual_alloc_re.search(page_text)):
            continue
        lines = page_text.splitlines()
        for i, line in enumerate(lines):
            if not (_ANGANWADI_RE.search(line) or _ICDS_RE.search(line)):
                continue
            # Try single line only (strict decimal amounts >= 100)
            amounts = _extract_amounts_from_line(line, min_val=100)
            if len(amounts) >= 2:
                return amounts[0], amounts[1], "medium", None
            # Try including integers on this line (handles split-column PDFs)
            clean_line = re.sub(r"[\d,]+\.?\d*\s*%", "", line)
            raw_line = [_parse_float(m) for m in _INT_OR_FLOAT_RE.findall(clean_line)]
            big_line = [a for a in raw_line if a and a >= 100]
            if len(big_line) >= 2:
                return big_line[0], big_line[1], "medium", None
            # Last resort: include next line (for word-wrapped scheme names)
            combined = " ".join(lines[i : i + 2])
            amounts2 = _extract_amounts_from_line(combined, min_val=100)
            if len(amounts2) >= 2:
                return amounts2[0], amounts2[1], "medium", None

    # ---- Strategy 3: heuristic — anganwadi/ICDS line preceded by large-figure rows ----
    # Only look at the scheme-name line itself (not joined), and require amounts > 500 cr
    # to avoid picking up sub-component or nutrition-supplement figures.
    lines = full_text.splitlines()
    for i, line in enumerate(lines):
        if not (_ANGANWADI_RE.search(line) or _ICDS_RE.search(line)):
            continue
        # Try the current line alone first
        amounts = _extract_amounts_from_line(line, min_val=500)
        if len(amounts) >= 2:
            big_sorted = sorted(amounts, reverse=True)
            return big_sorted[0], big_sorted[1], "low", None
        # Then look at the full 3-line window
        combined = " ".join(lines[i : i + 3])
        amounts = _extract_amounts_from_line(combined, min_val=500)
        if len(amounts) >= 2:
            big_sorted = sorted(amounts, reverse=True)
            return big_sorted[0], big_sorted[1], "low", None

    return None, None, "none", "no matching table found"


# Manual overrides for reports where pdfplumber misparses the allocation table.
# Each entry is keyed by report_no and provides verified values with an explanation.
_MANUAL_OVERRIDES = {
    314: {
        # 2020-21: pdfplumber split "20,532.38" as "2053 2.38" across PDF columns.
        # Source: Report 314 page 9, S.No.1 row: "Anganwadi Services 24810.00 2053 2.38"
        "mwcd_projected_cr": 24810.00,
        "finance_allocated_cr": 20532.38,
        "confidence": "medium",
        "note": "manual: pdfplumber split 20532.38 as '2053 2.38'",
    },
    326: {
        # 2021-22: ICDS sub-schemes regrouped into Saksham Anganwadi + POSHAN 2.0.
        # MWCD projection = sum of old schemes projected to MoF (Table IV):
        #   Anganwadi 20532.38 + Poshan 3700 + SAG 250 + Creche 75 = 24557.38
        # Finance allocated new combined scheme (BE 2021-22) = 20105.00 (Report 326, p.19-20)
        "mwcd_projected_cr": 24557.38,
        "finance_allocated_cr": 20105.00,
        "confidence": "medium",
        "note": "manual: combined pre-POSHAN projection; Finance allocated new POSHAN 2.0 BE",
    },
    338: {
        # 2022-23: Report 338 contains two projection tables. Strategy 2 matched
        # an earlier table (26930 vs 20105) which is historical 2021-22 comparison data.
        # The labeled section "2.4.1 Statement for F.Y. 2022-23" (p.23) gives the actual
        # 2022-23 DFG: Projected 20258.17, Actual Allocation (BE) 20263.07.
        # Cross-checked: Report 350 Table II confirms BE 2022-23 = 20263.07 for Saksham
        # Anganwadi & POSHAN 2.0. Finance honored the projection (MWCD self-censored ask).
        "mwcd_projected_cr": 20258.17,
        "finance_allocated_cr": 20263.07,
        "confidence": "high",
        "note": "manual: Table 2.4.1 p.23; cross-checked via Report 350 Table II BE 2022-23",
    },
    350: {
        # 2023-24: Report mis-classified as "other"; Strategy 3 matched Table II
        # historical figures instead of Table IV (Projected Demand vs Actual Allocation).
        # Source: Report 350 p.18, Table IV:
        #   Saksham Anganwadi Services and Poshan 2.0: Projected 22289.00, Allocated (BE) 20554.31
        "mwcd_projected_cr": 22289.00,
        "finance_allocated_cr": 20554.31,
        "confidence": "medium",
        "note": "manual: Table IV p.18; extractor matched wrong table (historical BE column)",
    },
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--manifest",
        default="data/icds_sansad_committees/manifest.jsonl",
    )
    parser.add_argument(
        "--pdf-dir",
        default="data/icds_sansad_committees/pdfs/rs",
    )
    parser.add_argument(
        "--output",
        default="data/dfg_projection_timeseries.csv",
    )
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    pdf_dir = Path(args.pdf_dir)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Load and filter manifest: DFG report_type + women/child in title.
    # Also accept report_type=="other" when the title explicitly names DFG/Demands for Grants
    # (e.g. Report 350 on DFG 2023-24 was mis-classified as "other").
    reports = []
    with manifest_path.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            rtype = rec.get("report_type", "")
            title_lower = rec.get("title", "").lower()
            if rtype == "demands_for_grants":
                pass  # always include
            elif rtype == "other" and (
                "demands for grants" in title_lower or " dfg " in title_lower
            ):
                pass  # mis-classified DFG report (e.g. Report 350)
            else:
                continue
            if not ("women" in title_lower or "child" in title_lower):
                continue
            reports.append(rec)

    print(f"Found {len(reports)} MWCD DFG reports in manifest")

    rows = []
    hits = []
    misses = []

    for rec in sorted(reports, key=lambda r: r.get("report_no", 0)):
        report_no = rec.get("report_no")
        title = rec.get("title", "")
        year = _year_from_title(title)
        pdf_rel = rec.get("pdf_path") or ""
        if not pdf_rel:
            misses.append((report_no, year, "no pdf_path in manifest"))
            rows.append(
                dict(
                    year=year,
                    report_no=report_no,
                    mwcd_projected_cr="",
                    finance_allocated_cr="",
                    cut_pct="",
                    source_pdf="",
                    confidence="none",
                    note="no pdf_path in manifest",
                )
            )
            continue
        # pdf_path in manifest is relative to data dir; resolve from pdf-dir
        pdf_filename = Path(pdf_rel).name
        pdf_path = pdf_dir / pdf_filename

        if not pdf_path.exists():
            print(f"  MISSING PDF: {pdf_filename}")
            misses.append((report_no, year, "pdf not found"))
            rows.append(
                dict(
                    year=year,
                    report_no=report_no,
                    mwcd_projected_cr="",
                    finance_allocated_cr="",
                    cut_pct="",
                    source_pdf=pdf_filename,
                    confidence="none",
                    note="pdf not found",
                )
            )
            continue

        if report_no in _MANUAL_OVERRIDES:
            ov = _MANUAL_OVERRIDES[report_no]
            projected, allocated, confidence, note = (
                ov["mwcd_projected_cr"],
                ov["finance_allocated_cr"],
                ov["confidence"],
                ov["note"],
            )
        else:
            projected, allocated, confidence, note = extract_from_pdf(pdf_path)

        cut_pct = ""
        if projected and allocated and projected > 0:
            cut_pct = round((allocated - projected) / projected * 100, 2)

        rows.append(
            dict(
                year=year,
                report_no=report_no,
                mwcd_projected_cr=projected if projected else "",
                finance_allocated_cr=allocated if allocated else "",
                cut_pct=cut_pct,
                source_pdf=pdf_filename,
                confidence=confidence,
                note=note or "",
            )
        )

        if confidence in ("high", "medium", "low"):
            hits.append((report_no, year, confidence, projected, allocated, cut_pct))
        else:
            misses.append((report_no, year, note))

    # Write CSV
    fieldnames = [
        "year",
        "report_no",
        "mwcd_projected_cr",
        "finance_allocated_cr",
        "cut_pct",
        "source_pdf",
        "confidence",
        "note",
    ]
    with output_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"\nOutput written to {output_path}")
    print(f"\n{'='*60}")
    print(f"SUCCESSFULLY EXTRACTED ({len(hits)} reports):")
    print(f"{'='*60}")
    print(f"{'No':>5}  {'Year':<10}  {'Conf':<8}  {'MWCD Proj':>12}  {'Fin Alloc':>12}  {'Cut%':>8}")
    for no, yr, conf, proj, alloc, cut in sorted(hits, key=lambda x: x[1] or ""):
        print(f"{no:>5}  {str(yr):<10}  {conf:<8}  {str(proj):>12}  {str(alloc):>12}  {str(cut):>8}")

    print(f"\n{'='*60}")
    print(f"MISSED / NO EXTRACTION ({len(misses)} reports):")
    print(f"{'='*60}")
    for no, yr, note in misses:
        print(f"  Report {no} ({yr}): {note}")


if __name__ == "__main__":
    main()
