"""
Generated by: budget_crawler/icds_inflation_table.py
DO NOT HAND-EDIT — rerun to regenerate output.

Builds a 10-year inflation-adjusted timeseries for ICDS / Saksham Anganwadi:
- MWCD demanded (from DFG projection timeseries)
- Finance allocated BE (from DFG projection timeseries)
- Actual expenditure (from SBE XLS timeseries)
- % of allocated BE that was spent
- All figures in 2011-12 constant prices (NAS implicit GDP deflator, GOI standard)

Deflator methodology: MoSPI NAS GDP implicit price deflator, base 2011-12=100.
Formula: real_value = nominal_value × (100 / deflator)
Best revision selected per year (Final > Third Revised > Second Revised > First Revised > Provisional > Advance).
Source: MoSPI NAS API, indicator_code=5 (GDP), base_year=2011-12, series=Current + Back.
Fetched: 2026-05-16.

Sources:
  data/dfg_projection_timeseries.csv  — demanded + allocated BE
  data/icds_budget_timeseries.csv     — BE + actuals (2021-22 onwards)
  MoSPI NAS API (GDP deflator, 2011-12 base)
  CPR Accountability Initiative Budget Briefs (2016-17, 2022-23)
"""

import csv
from pathlib import Path

# ---- NAS implicit GDP deflator (2011-12 = 100) ----
# deflator = (GDP at current prices / GDP at constant 2011-12 prices) × 100
# Best revision per year. Source: MoSPI NAS API fetched 2026-05-16.
# 2025-26 is First Advance Estimates (preliminary).
_NAS_DEFLATOR = {
    "2010-11": round(7634472.10 / 8301234.84 * 100, 2),   # Back series
    "2011-12": 100.00,                                      # base year by definition
    "2012-13": round(9944013.10 / 9213016.66 * 100, 2),   # Additional Revision
    "2013-14": round(11233521.61 / 9801369.88 * 100, 2),  # Additional Revision
    "2014-15": round(12467959.29 / 10527673.63 * 100, 2), # Third Revised
    "2015-16": round(13771873.88 / 11369493.14 * 100, 2), # Third Revised
    "2016-17": round(15391669.00 / 12308193.00 * 100, 2), # Third Revised
    "2017-18": round(17090042.36 / 13144582.14 * 100, 2), # Third Revised
    "2018-19": round(18899668.44 / 13992913.94 * 100, 2), # Third Revised
    "2019-20": round(20103592.86 / 14534640.78 * 100, 2), # Third Revised
    "2020-21": round(19854096.01 / 13694869.24 * 100, 2), # Third Revised
    "2021-22": round(23597398.53 / 15021846.27 * 100, 2), # Second Revised
    "2022-23": round(26890472.57 / 16164913.38 * 100, 2), # Final Estimates
    "2023-24": round(30122955.90 / 17650590.95 * 100, 2), # First Revised
    "2024-25": round(33068145.37 / 18796955.44 * 100, 2), # Provisional
    "2025-26": round(35713886.24 / 20189918.88 * 100, 2), # First Advance (preliminary)
}


def main():
    data_dir = Path("data")

    # ---- CPR Accountability Initiative historical data ----
    # Source: ICDS Budget Brief Vol 8/Issue 4 (2016-17) + Saksham Anganwadi Budget Brief Vol 14/Issue 1 (2022-23)
    # Scope: FULL GOI ICDS envelope — includes SNP, core ICDS, all sub-schemes (broader than DFG Anganwadi Services line).
    # Pre-2021: ICDS + POSHAN Abhiyaan + SAG + Creche as separate GOI schemes combined.
    # Post-2021: Saksham Anganwadi + POSHAN 2.0 umbrella (same as SBE data).
    # These are Revised Estimates (RE) unless marked BE. Use for narrative context only — not directly comparable
    # to DFG "demanded vs allocated" figures which track Anganwadi Services demand to Finance Ministry.
    _CPR_FULL_SCHEME = {
        "2010-11": {"allocated_re_cr": 9280,  "source": "CPR ICDS Brief 2016-17"},
        "2011-12": {"allocated_re_cr": 14048, "source": "CPR ICDS Brief 2016-17"},
        "2012-13": {"allocated_re_cr": 16312, "source": "CPR ICDS Brief 2016-17"},
        "2013-14": {"allocated_re_cr": 16561, "source": "CPR ICDS Brief 2016-17"},
        "2014-15": {"allocated_re_cr": 15850, "source": "CPR ICDS Brief 2016-17"},
        "2015-16": {"allocated_re_cr": 15502, "note": "BE was 8336; supplementary budgets added 7166", "source": "CPR ICDS Brief 2016-17"},
        "2016-17": {"allocated_be_cr": 14000, "source": "CPR ICDS Brief 2016-17"},
        # 2017-18 and 2018-19: chart values from CPR 2022-23 brief (stacked bar, REs)
        "2017-18": {"allocated_re_cr": 16720, "source": "CPR Saksham Brief 2022-23 chart"},
        "2018-19": {"allocated_re_cr": 17917, "source": "CPR Saksham Brief 2022-23 chart"},
        # 2019-20: ICDS RE 17705 + POSHAN RE 3400 (from CPR 2022-23 brief p.3)
        "2019-20": {"allocated_re_cr": 21105, "note": "ICDS 17705 + POSHAN 3400 (RE)", "source": "CPR Saksham Brief 2022-23"},
        # 2020-21: ICDS RE 17252 + POSHAN RE 600 (massive POSHAN underspend due to COVID)
        "2020-21": {"allocated_re_cr": 17852, "note": "ICDS 17252 + POSHAN 600 (RE); POSHAN badly underspent in COVID year", "source": "CPR Saksham Brief 2022-23"},
        # 2021-22 onwards: Saksham Anganwadi + POSHAN 2.0 umbrella (same scope as SBE data)
        "2021-22": {"allocated_re_cr": 20000, "source": "CPR Saksham Brief 2022-23"},
        "2022-23": {"allocated_be_cr": 20263, "source": "CPR Saksham Brief 2022-23"},
    }

    # ---- Load DFG projection timeseries (demanded + allocated) ----
    dfg = {}
    with open(data_dir / "dfg_projection_timeseries.csv") as f:
        for row in csv.DictReader(f):
            yr = row["year"]
            if not yr or not row["mwcd_projected_cr"] or not row["finance_allocated_cr"]:
                continue
            # Only years in range we care about: 2015-16 to 2025-26
            start = int(yr[:4])
            if start < 2015 or start > 2025:
                continue
            dfg[yr] = {
                "demanded_cr": float(row["mwcd_projected_cr"]),
                "allocated_be_cr": float(row["finance_allocated_cr"]),
                "dfg_confidence": row["confidence"],
            }

    # ---- Load SBE actuals timeseries ----
    sbe = {}
    with open(data_dir / "icds_budget_timeseries.csv") as f:
        for row in csv.DictReader(f):
            fy = row["fiscal_year"]
            col = row["col_type"]
            total = float(row["total_cr"]) if row["total_cr"] else 0.0
            if col == "actual" and total > 0:
                sbe[fy] = {"actual_cr": total}
            elif col == "be" and fy not in sbe:
                # fallback: record the BE if no actual yet
                sbe.setdefault(fy, {})["sbe_be_cr"] = total

    print(f"\nNAS implicit GDP deflator (2011-12=100, GOI standard):")
    for fy, d in sorted(_NAS_DEFLATOR.items()):
        print(f"  {fy}: {d:.2f}")

    # ---- Assemble the table ----
    # Two sections:
    #   A. Full-scheme historical (CPR data, 2013-14 to 2020-21): full GOI ICDS envelope (RE)
    #   B. Focused decade DFG+SBE (2016-17 to 2025-26): Anganwadi Services demand + Saksham umbrella actuals
    # From 2021-22 onwards scopes converge (both track Saksham Anganwadi + POSHAN 2.0 umbrella).

    all_years_full = [
        "2013-14", "2014-15", "2015-16", "2016-17", "2017-18", "2018-19", "2019-20",
        "2020-21", "2021-22", "2022-23", "2023-24", "2024-25", "2025-26",
    ]

    rows = []
    for fy in all_years_full:
        d = dfg.get(fy, {})
        s = sbe.get(fy, {})
        c = _CPR_FULL_SCHEME.get(fy, {})
        deflator = _NAS_DEFLATOR.get(fy)

        demanded = d.get("demanded_cr")
        allocated_dfg_be = d.get("allocated_be_cr")
        allocated_cpr_re = c.get("allocated_re_cr") or c.get("allocated_be_cr")
        actual = s.get("actual_cr")
        sbe_be = s.get("sbe_be_cr")
        if not allocated_dfg_be and sbe_be:
            allocated_dfg_be = sbe_be

        pct_spent = None
        if actual and allocated_dfg_be and allocated_dfg_be > 0:
            pct_spent = round(actual / allocated_dfg_be * 100, 1)

        demanded_cut = None
        if demanded and allocated_dfg_be and demanded > 0:
            demanded_cut = round((allocated_dfg_be - demanded) / demanded * 100, 1)

        def deflate(val):
            if val is None or deflator is None:
                return None
            return round(val * 100 / deflator, 0)

        rows.append({
            "fiscal_year": fy,
            "demanded_nominal_cr": demanded,
            "allocated_dfg_be_cr": allocated_dfg_be,
            "allocated_cpr_full_re_cr": allocated_cpr_re,
            "actual_nominal_cr": actual,
            "pct_spent_of_allocated": pct_spent,
            "demanded_cut_pct": demanded_cut,
            "nas_deflator_2011_12_100": deflator,
            "demanded_real_cr_2011_12": deflate(demanded),
            "allocated_dfg_be_real_cr_2011_12": deflate(allocated_dfg_be),
            "allocated_cpr_full_real_cr_2011_12": deflate(allocated_cpr_re),
            "actual_real_cr_2011_12": deflate(actual),
            "dfg_confidence": d.get("dfg_confidence", ""),
            "cpr_note": c.get("note", ""),
        })

    # ---- Print table A: CPR full-scheme historical (nominal + real) ----
    print(f"\n{'='*90}")
    print("TABLE A — Full GOI ICDS Scheme (CPR data): 2013-14 to 2025-26")
    print("Scope: Full GOI envelope — SNP + core ICDS + POSHAN Abhiyaan + SAG + Creche (pre-2021 RE; post-2021 = Saksham umbrella)")
    print(f"{'='*90}")
    print(f"{'FY':<9}  {'CPR Full (RE/BE)':>18}  {'CPR Real (2011-12₹)':>21}  {'Deflator':>9}")
    print("-" * 65)
    for r in rows:
        cpr = r["allocated_cpr_full_re_cr"]
        cpr_real = r["allocated_cpr_full_real_cr_2011_12"]
        defl = r["nas_deflator_2011_12_100"]
        defl_str = f"{defl:>8.2f}" if defl else f"{'—':>9}"
        print(
            f"{r['fiscal_year']:<9}  "
            f"{(f'{cpr:>16,.0f}' if cpr else f'{'—':>18}'):>18}  "
            f"{(f'{cpr_real:>19,.0f}' if cpr_real else f'{'—':>21}'):>21}  "
            f"{defl_str}"
        )

    # ---- Print table B: DFG demanded vs allocated + actuals ----
    print(f"\n{'='*110}")
    print("TABLE B — MWCD Demanded vs Finance Allocated + Actual Expenditure: 2016-17 to 2025-26")
    print("Scope: 'Demanded' = Anganwadi Services line (DFG reports). 'Alloc BE' = Finance Ministry BE.")
    print("       'Actual' = Saksham Anganwadi+POSHAN 2.0 umbrella (SBE XLS, 2021-22 onwards).")
    print(f"{'='*110}")
    print(
        f"{'FY':<9}  {'Demanded':>10}  {'Alloc BE':>10}  {'Actual':>10}  "
        f"{'%Spent':>7}  {'%Cut':>7}  "
        f"{'Dem Real':>10}  {'BE Real':>10}  {'Act Real':>10}"
    )
    print("-" * 110)
    for r in rows:
        if int(r["fiscal_year"][:4]) < 2016:
            continue

        def fmt(v):
            return f"{v:>10,.0f}" if v is not None else f"{'—':>10}"
        def fmtp(v):
            return f"{v:>7.1f}" if v is not None else f"{'—':>7}"

        print(
            f"{r['fiscal_year']:<9}  {fmt(r['demanded_nominal_cr'])}  "
            f"{fmt(r['allocated_dfg_be_cr'])}  {fmt(r['actual_nominal_cr'])}  "
            f"{fmtp(r['pct_spent_of_allocated'])}  {fmtp(r['demanded_cut_pct'])}  "
            f"{fmt(r['demanded_real_cr_2011_12'])}  {fmt(r['allocated_dfg_be_real_cr_2011_12'])}  "
            f"{fmt(r['actual_real_cr_2011_12'])}"
        )

    print(f"\nAll figures ₹ crore. Real = 2011-12 constant prices (NAS implicit GDP deflator, GOI standard).")
    print(f"Sources: MoSPI NAS API (GDP deflator); CPR Accountability Initiative Budget Briefs (2016-17, 2022-23);")
    print(f"         RS Education Committee DFG reports; Union Budget SBE XLS Demand No. 101.")
    print(f"Note: 2025-26 deflator is First Advance Estimates (preliminary).")

    # ---- Write CSV ----
    out_path = data_dir / "icds_inflation_adjusted_timeseries.csv"
    fieldnames = [
        "fiscal_year", "demanded_nominal_cr", "allocated_dfg_be_cr", "allocated_cpr_full_re_cr",
        "actual_nominal_cr", "pct_spent_of_allocated", "demanded_cut_pct",
        "nas_deflator_2011_12_100",
        "demanded_real_cr_2011_12", "allocated_dfg_be_real_cr_2011_12",
        "allocated_cpr_full_real_cr_2011_12", "actual_real_cr_2011_12",
        "dfg_confidence", "cpr_note",
    ]
    with open(out_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)
    print(f"\nCSV written: {out_path}")


if __name__ == "__main__":
    main()
