"""Instance overlay: attach a state-year's actual rupees to the inter-tier flow graph.

Reuses the existing balance Sankey output (built by viz/build_sankey.py from the
state's own books) for the amounts — does NOT re-derive them. Maps each balance
source onto a references/flow_graph/ edge by edge_id, then writes:

  references/flow_graph/instances/<state>_<fy>.json   — edges with amount_cr
  references/flow_graph/instances/<state>_<fy>.html   — a vertical Sankey
    (Union tier -> State exchequer -> Uses), reusing CDN d3-sankey like flow.html.

    python -m viz.build_flow_overlay --state gujarat --fy 2024-25

Amounts inherit the source Sankey's caveat (indicative; not line-verified).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
LOD = REPO / "references" / "lmmha" / "lod"
OUT = REPO / "references" / "flow_graph" / "instances"

# Balance-Sankey source node name -> flow_graph edge_id. Tracks the node names the
# balance adapter emits (viz/sankey/adapters/*). Update here if those names change.
BALANCE_SOURCE_TO_EDGE = {
    "Own tax": "own.state",
    "Own non-tax": "own.state_nontax",
    "Tax devolution": "devolution.union_state",
    "Grants from Centre": "fcgrant.union_state",
    "Net borrowing": "borrow.market_state",
}
# which sources originate at the Union tier (for the vertical column)
UNION_ORIGIN = {"devolution.union_state", "fcgrant.union_state"}


def load_balance(state: str, fy: str) -> dict:
    f = LOD / f"sankey_{state}_balance_{fy}.json"
    if not f.exists():
        raise SystemExit(f"no balance Sankey at {f} — build it first: "
                         f"python -m viz.build_sankey --state {state} --fy {fy} --view balance")
    return json.loads(f.read_text())


def overlay(state: str, fy: str) -> dict:
    bal = load_balance(state, fy)
    edges = {e["edge_id"]: e for e in
             json.loads((REPO / "references/flow_graph/edges.json").read_text())["edges"]}
    nodes = bal["nodes"]
    name = lambda i: nodes[i]["name"] if isinstance(i, int) else i

    sources, uses = [], []
    for l in bal["links"]:
        s, t = name(l["source"]), name(l["target"])
        if t == nodes[0]["name"]:                 # source -> exchequer
            eid = BALANCE_SOURCE_TO_EDGE.get(s)
            if not eid:
                raise SystemExit(f"unmapped balance source '{s}' — add it to BALANCE_SOURCE_TO_EDGE")
            e = edges[eid]
            sources.append({"edge_id": eid, "label": s, "amount_cr": round(l["value"], 1),
                            "from": e["from"], "concept_id": e["concept_id"],
                            "lands_under": e.get("lands_under"), "union_origin": eid in UNION_ORIGIN})
        else:                                     # exchequer -> use
            uses.append({"label": t, "amount_cr": round(l["value"], 1)})

    from_centre = round(sum(s["amount_cr"] for s in sources if s["union_origin"]), 1)
    total = round(sum(s["amount_cr"] for s in sources), 1)
    return {
        "generated_by": "viz/build_flow_overlay.py",
        "state": bal["meta"]["state"], "fy": bal["meta"]["fy"], "unit": "INR crore",
        "total_cr": total, "from_centre_cr": from_centre,
        "from_centre_pct": round(100 * from_centre / total, 1),
        "sources": sources, "uses": uses,
        "source_doc": bal["meta"].get("source"),
        "caveat": bal["meta"].get("caveat", "") + " Overlay maps balance sources onto references/flow_graph/ edges.",
    }


def sankey_json(ov: dict) -> dict:
    """Vertical Sankey shape: Union -> transfer streams -> exchequer -> uses."""
    ex = f"{ov['state']} exchequer"
    nodes, idx = [], {}
    def node(n, color):
        if n not in idx:
            idx[n] = len(nodes); nodes.append({"name": n, "color": color})
        return idx[n]
    node("Union (Centre)", "#3b6fb0"); node(ex, "#444")
    links = []
    for s in ov["sources"]:
        col = "#3b6fb0" if s["union_origin"] else ("#b03a3a" if s["from"] == "economy" and "borrow" in s["edge_id"] else "#2f8f8f")
        node(s["label"], col)
        if s["union_origin"]:
            links.append({"source": idx["Union (Centre)"], "target": idx[s["label"]], "value": s["amount_cr"]})
        links.append({"source": idx[s["label"]], "target": idx[ex], "value": s["amount_cr"]})
    for u in ov["uses"]:
        node(u["label"], "#6c6f7d")
        links.append({"source": idx[ex], "target": idx[u["label"]], "value": u["amount_cr"]})
    return {"nodes": nodes, "links": links}


HTML = """<!-- generated by viz/build_flow_overlay.py — do not hand-edit -->
<!doctype html><html lang=en><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>{state} money flow {fy} — vertical Sankey</title>
<style>body{{font:15px/1.5 system-ui,sans-serif;margin:1.5rem;max-width:1000px}}
.link{{fill:none;stroke:#000;stroke-opacity:.18}}.link:hover{{stroke-opacity:.4}}
text{{font-size:12px}} .cap{{color:#a33;font-size:13px}} h1{{font-size:1.25rem}}</style>
</head><body>
<h1>{state} — where the money comes from and goes, {fy}</h1>
<p><b>{pct}% originates at the Centre</b> (₹{centre} cr of ₹{total} cr): tax devolution + grants.
Own revenue and market borrowing make up the rest.</p>
<svg id=s></svg>
<p class=cap>Indicative — built from {state}'s own budget books via the balance Sankey; not line-verified. {caveat}</p>
<script src="https://cdn.jsdelivr.net/npm/d3@7.9.0/dist/d3.min.js" integrity="sha384-CjloA8y00+1SDAUkjs099PVfnY2KmDC2BZnws9kh8D/lX1s46w6EPhpXdqMfjK6i" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/d3-sankey@0.12.3/dist/d3-sankey.min.js" integrity="sha384-SM54CE5h+qdDI046d2Y5ym7wq1kq4uxcQ1cqGq5/+5jrE5tPLeDJSq711Q8sIska" crossorigin="anonymous"></script>
<script>
const data={data};
const W=940,H=Math.max(420,data.links.length*26+40);
const svg=d3.select("#s").attr("viewBox",`0 0 ${{W}} ${{H}}`).style("width","100%");
const sk=d3.sankey().nodeWidth(14).nodePadding(14).extent([[8,8],[W-160,H-8]]);
const g=sk({{nodes:data.nodes.map(d=>({{...d}})),links:data.links.map(d=>({{...d}}))}});
svg.append("g").selectAll("path").data(g.links).join("path").attr("class","link")
 .attr("d",d3.sankeyLinkHorizontal()).attr("stroke-width",d=>Math.max(1,d.width));
const n=svg.append("g").selectAll("g").data(g.nodes).join("g");
n.append("rect").attr("x",d=>d.x0).attr("y",d=>d.y0).attr("height",d=>d.y1-d.y0)
 .attr("width",d=>d.x1-d.x0).attr("fill",d=>d.color);
n.append("text").attr("x",d=>d.x0<W/2?d.x1+6:d.x0-6).attr("y",d=>(d.y0+d.y1)/2)
 .attr("dy","0.35em").attr("text-anchor",d=>d.x0<W/2?"start":"end")
 .text(d=>`${{d.name}} ₹${{d3.format(",.0f")(d.value)}} cr`);
</script></body></html>
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--state", default="gujarat")
    ap.add_argument("--fy", default="2024-25")
    a = ap.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    ov = overlay(a.state, a.fy)
    (OUT / f"{a.state}_{a.fy}.json").write_text(json.dumps(ov, indent=2, ensure_ascii=False))
    sj = sankey_json(ov)
    html = HTML.format(state=ov["state"], fy=ov["fy"], pct=ov["from_centre_pct"],
                       centre=f'{ov["from_centre_cr"]:,.0f}', total=f'{ov["total_cr"]:,.0f}',
                       caveat="", data=json.dumps(sj, ensure_ascii=False))
    (OUT / f"{a.state}_{a.fy}.html").write_text(html)
    print(f"wrote {OUT}/{a.state}_{a.fy}.json  ({ov['from_centre_pct']}% from Centre, "
          f"₹{ov['total_cr']:,.0f} cr total) and .html")


if __name__ == "__main__":
    main()
